version: '3.3'
services:
  vue:
    build:
      context: .
    ports:
      - '127.0.0.1:8080:80'
    env_file: 
      .env
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
    external:
      name: backend