version: '3.3'
services:
  dd-frontend:
    container_name: danieldevine.dev-frontend
    build:
      context: .
      args: 
        NODE_ENV: development
      target: dev
    volumes:
      - './:/app/'
    ports:
      - '8080:8080'
    restart: unless-stopped
    entrypoint: "yarn" 
    command: "serve"
