version: '3.3'
services:
  vue_production:
    # name: 'frontend-production.danieldevine.dev'
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - './:/app/'
    ports:
      - '8080:8080'
    restart: unless-stopped
    entrypoint: ["yarn", "serve"]
