version: '3.3'
services:
  strapi_backend:
    build:
      context: ./backend/.
      args: 
        NODE_ENV: ${NODE_ENV}
        PORT: 10000
    # ports:
    #   - '10000:10000'
    volumes:
      - 'strapi_production_public:/app/public'
    env_file: 
      backend.env
    # external_links:
    #   - mariadb_server:mysql
    restart: unless-stopped
  vue_frontend:
    # name: 'frontend-production.danieldevine.dev'
    build:
      context: ./frontend/.
      args: 
        NODE_ENV: ${NODE_ENV}
    # ports:
      # - '10001:80'
    env_file: 
      frontend.env
    restart: unless-stopped
    depends_on:
      - strapi_backend
volumes:
  strapi_production_public:
    external: true