version: '3.3'
services:
  dd-backend:
    container_name: danieldevine.dev-backend
    build:
      context: ./backend/.
      args: 
        NODE_ENV: development
      target: dev
    ports:
      - '1337:1337'
    volumes:
      - './backend/public:/app/public'
      - './backend/.tmp:/app/.tmp'
      - './backend/api:/app/api'
      - './backend/components:/app/components'
      - './backend/config:/app/config'
      - './backend/extensions:/app/extensions'
    restart: unless-stopped
    entrypoint: "yarn"
    command: "develop"

  dd-frontend:
    container_name: danieldevine.dev-frontend
    build:
      context: ./frontend/.
      args: 
        NODE_ENV: development
      target: dev
    volumes:
      - './frontend/:/app/'
    ports:
      - '8080:8080'
    restart: unless-stopped
    entrypoint: "yarn" 
    command: "serve"
    depends_on: 
      - "dd-backend"