version: '3.3'
services:
  strapi:
    build: .
    ports:
      - '127.0.0.1:1337:1337'
    volumes:
      - '`pwd`:/srv/app'
    
    env_file: 
      .env
    # image: strapi/strapi
    networks:
      - backend

networks:
  backend:
    external:
      name: backend