version: '3'

services:
  strapi-api:
    build:
      context: .
      args: 
        STRAPI_VERSION: '3.0.0-beta.20'
    container_name: strapi-api
    env_file: 
      .env
    ports:
      - '127.0.0.1:1337:1337'
    volumes:
      - ./:/usr/src/app
    networks:
      - backend

networks:
  backend:
    external:
      name: backend