version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    env_file: 
      .env
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    depends_on:
      - db
