version: '3.3'
services:
  dd-backend:
    container_name: danieldevine.dev-backend
    build:
      context: .
      args: 
        NODE_ENV: development
    ports:
      - '1337:1337'
    volumes:
      - './public:/app/public'
      - './.tmp:/app/.tmp'
      - './api:/app/api'
      - './components:/app/components'
      - './config:/app/config'
      - './extensions:/app/extensions'
    restart: unless-stopped
    entrypoint: "yarn"
    command: "develop"
