version: '3'

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      - VIRTUAL_HOST=api.dev.danieldevine.dev
      - LETSENCRYPT_HOST=api.dev.danieldevine.dev
      - VIRTUAL_PORT=1337
    env_file: 
      .env
    ports:
      - '127.0.0.1:1337:1337'
    
    volumes:
      - ./:/srv/app
    depends_on:
      - db


networks:
  backend:
    external:
      name: backend