version: '3.3'
services:
  strapi:
    build: .
    ports:
      - '127.0.0.1:1337:1337'
    volumes:
      - './:/srv/app'
      - 'staging_public_files:/app/public'
    env_file: 
      .env
    networks:
      - backend
    external_links:
        - mariadb_server:mysql
    restart: unless-stopped
volumes:
  staging_public_files:
    external: true
networks:
  backend:
    external:
      name: backend
