version: '3'

services:
  strapi:
    build:
      context: .
    container_name: strapi
    environment:
      - VIRTUAL_HOST=api.dev.danieldevine.dev
      - LETSENCRYPT_HOST=api.dev.danieldevine.dev
      - VIRTUAL_PORT=1337
    env_file: 
      .env
    ports:
      - '127.0.0.1:1337:1337'
    volumes:
      - ./:/usr/src/app
    networks:
      - backend

networks:
  backend:
    external:
      name: backend