name: Production API & UI Updates
#
#on:
#    pull_request:
#        branches: [ production ]
#
#jobs:
#    execute_update_commands:
#        runs-on: ubuntu-latest
#        steps:
#        -   name: pull updates
#            uses: garygrossgarten/github-action-ssh@release
#            with:
#                host: ${{ secrets.STAGING_HOST }}
#                username: ${{ secrets.STAGING_USERNAME }}
#                privateKey: ${{ secrets.STAGING_KEY }}
#                command: ~/production.danieldevine.dev/.github/deploy.sh production ~/production.danieldevine.dev