name: Staging API Update

on:
    pull_request:
        branches: [ STAGING ]

jobs:
    execute_update_commands:
        runs-on: ubuntu-latest
        steps:
        -   name: pull updates
            uses: garygrossgarten/github-action-ssh@release
            with:
                host: ${{ secrets.STAGING_HOST }}
                username: ${{ secrets.STAGING_USERNAME }}
                privateKey: ${{ secrets.STAGING_KEY }}
                command: ${{ secrets.STAGING_DIRECTORY }}/.github/deploy.sh staging ${{ secrets.STAGING_DIRECTORY }}