name: Staging API Update

on:
    pull_request:
        branches: [ STAGING ]

jobs:
    execute_update_commands:
        runs-on: ubuntu-latest
        steps:
        -   name: connect and pull updates
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.STAGING_HOST }}
                key: ${{ secrets.STAGING_KEY }}
                script: |
                    whoami
                    ls -al